let regFirst = new RegExp("abc");
let regSecond = /abc/;
let eighteenPlus = /eighteen\+/;
console.log(regSecond.test("abccaddkk"));
console.log(regSecond.test("adccaddkk"));
console.log(/[0-9]/.test("this d"));
let regD = /\w\w\w\s\w\w/;
console.log(regD.test("fff dd asdf  asdfdsdssda d"));
let notBinary = /[^45]/;
console.log("есть ли кроме 45 что-нибудь: ", notBinary.test("454545454444555"));
console.log(/'\d+'/.test("'31654'"));
console.log(/'\d+'/.test("''"));
console.log(/'\d*'/.test("'31654'"));
console.log(/'\d*'/.test("''"));
let vl = /vlad?islav/;
console.log("vladislav test ",vl.test("vladislav"));
console.log(vl.test("vlaislav"));
let dateTime = /\d{1,4}-\w{1}-\d{1,4}/;
console.log(dateTime.test("4-d-1"));